### ISSUE TITLE
Error by decrypting a file with a different region datetime

### ISSUE THREAD

**Issue by blackfog84** [hibara/AttacheCase3#44]
Hello,

by decrpyting an ATC v3 file which was created on a PC with a different region DateTime i got an error at line 717 and 739 in source code file FileDecrpyt3.cs

The value of LastWriteTime is too large for AddSeconds method of DateTime.

As an example i attached a test file which i created on a system with german region DateTime. The password is 123.

[test.zip](https://github.com/hibara/AttacheCase3/files/1057732/test.zip)

Thank you very much!

**Comment by hibara** [comment]
Thank you for your bug report.

I confirmed the problem. This is because it was not supposed to decrypt the encrypted file in another locale.

It was solved by including the UTC date time in the encrypted file, but it applies only when encrypted with this new version or later.

https://hibara.org/software/attachecase/

When decrypting from an old encrypted file with the problem, it set the current date and time so as not to cause an error.
