### ISSUE TITLE
ver.3.4.0.0にて、パスワードの確認テキストボックスが有効化されない

### ISSUE THREAD

**Issue by SC-MAKERS** [hibara/AttacheCase3#58]
＜環境＞
・Windows 10 Pro (64bit)

＜現象＞
[動作設定]-[一般]-[パスワード]
暗号化時のパスワード保存機能におけるパスワード入力ダイアログにて、
パスワードを入力しても、[パスワードの確認]テキストボックスが有効化されません。
結果として、[OK]ボタンを押して入力を確定できません。

**v.3.4.0.0**
![at3400](https://user-images.githubusercontent.com/29565192/44889610-798af800-ad11-11e8-84f9-e17c2abc8baa.PNG)

v.3.3.0.0では、パスワード入力によって同テキストボックスが有効化されます。

**v.3.3.0.0**
![at3300](https://user-images.githubusercontent.com/29565192/44889625-8a3b6e00-ad11-11e8-88aa-0847a31d9f38.PNG)

**Comment by SC-MAKERS** [comment]
ソースコード（Form4.Desiner.cs）を拝読しましたところ、
下記イベントハンドラの登録処理が消えてしまっていることが要因かもしれません。

```cs
this.checkBoxNotMaskEncryptedPassword.CheckedChanged += new System.EventHandler(this.checkBoxNotMaskEncryptedPassword_CheckedChanged); 
// -- 中略 --
this.textBoxRePassword.TextChanged += new System.EventHandler(this.textBoxRePassword_TextChanged); 
// -- 中略 --
this.textBoxPassword.TextChanged += new System.EventHandler(this.textBoxPassword_TextChanged); 
// -- 中略 --
this.buttonPasswordCancel.Click += new System.EventHandler(this.buttonPasswordCancel_Click); 
// -- 中略 --
this.buttonPasswordOK.Click += new System.EventHandler(this.buttonPasswordOK_Click); 
```

**Comment by drkinchan** [comment]
私もまったく同様の現象に悩んでいます。
Windows 10 Home (64bit)です。
v.3.3.0.0に戻して使っています。

**Comment by hibara** [comment]
ご報告ありがとうございます！
また、修正に時間がかかって申し訳ありません。

先ほどこの問題を修正した最新版の方をアップロードさせていただきました。
下記よりご利用くださいませ。

アタッシェケース ver.3.4.1.0
https://hibara.org/software/attachecase/

**Comment by drkinchan** [comment]
Hibara様
金森です。ご丁寧にありがとうございます。
いつも助かっております。
新バージョン嬉しいです。使わせていただきます。


----- 元のメッセージ -----
From: "Mitsuhiro Hibara" <notifications@github.com>
宛先: "hibara/AttacheCase3" <AttacheCase3@noreply.github.com>
Cc: "drkinchan" <gokin60@yahoo.co.jp>, "Comment" <comment@noreply.github.com>
送信済み: 2018年10月10日, 水曜日 午前 9:56:36
件名: Re: [hibara/AttacheCase3] ver.3.4.0.0にて、パスワードの確認テキストボックスが有効化されない (#58)



ご報告ありがとうございます！ 
また、修正に時間がかかって申し訳ありません。 

先ほどこの問題を修正した最新版の方をアップロードさせていただきました。 
下記よりご利用くださいませ。 

アタッシェケース ver.3.4.1.0 
https://hibara.org/software/attachecase/ 

― 
You are receiving this because you commented. 
Reply to this email directly, view it on GitHub , or mute the thread . 

-- 
金森 剛
